spring.application.name=crud-jpa-demo
spring.datasource.url=jdbc:postgresql://ep-cool-night-a83dpfrz-pooler.eastus2.azure.neon.tech/neondb?user=neondb_owner&password=npg_QeKEqrhgUT87&sslmode=require
spring.jpa.hibernate.ddl-auto=update
